```{r echo = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

- Setup git

```{r}
usethis::git_sitrep()
gert::git_config_global_set("user.name", "js2264")
gert ::git_config_global_set("user.email", "jacquesserizay@gmail.com")
usethis ::git_vaccinate()
usethis ::use_git()
usethis ::use_git_ignore("*.Rproj")
```

- Setup github 

```{r}
gh::gh_whoami()
usethis::gh_token_help()

#Create a GH PAT
usethis::create_github_token()
gitcreds::gitcreds_set()
#Paste your GitHub token, not your password!

#Add an SSH key to GitHub 
usethis::use_github()
credentials::ssh_setup_github()
```

- Create an `SummarizedMotifs` S4 class in `AllClasses.R`

```{r}
library(GenomicRanges)
ATAC_peaks <- readRDS(here::here('../../../Share/Day1/ATAC_peaks.rds'))
granges <- ATAC_peaks[ATAC_peaks$annot != "non-DA"]
library(Biostrings)
library(BSgenome.Scerevisiae.UCSC.sacCer3)
seqs <- getSeq(BSgenome.Scerevisiae.UCSC.sacCer3)

library(SummarizedExperiment)
SM <- SummarizedMotifs(granges, seqs)
```

- Create an "odds" function in `stats.R`

```{r}
odds <- Odds(SM, group_by = rowData(SM)$annot)
```


