on:
  push:
     branches:
       - master

name: build_and_goto_gh_pages

jobs:
  blogdown:
    name: build_and_push_to_gh_pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown", "rmdformats", "tibble"))'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.81.0")'
      - name: build content
        run: Rscript -e "blogdown::build_dir('content/')"
      - name: build static
        run: Rscript -e "blogdown::build_dir('static/')"
      - name: build site
        run: Rscript -e 'blogdown::hugo_build(local = FALSE)'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
